#==================================================
# Build Layer
FROM node:16-slim as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile

COPY . .

RUN yarn build

#==================================================
# Package install Layer
FROM node:16-slim as node_modules

WORKDIR /app

COPY package.json yarn.lock ./
# COPY package.json package-lock.json ./

RUN yarn install --non-interactive --frozen-lockfile --prod

#==================================================
# Run Layer
FROM gcr.io/distroless/nodejs:16

WORKDIR /app

# パフォーマンスやセキュリティ関連の最適化を有効にするため
ENV NODE_ENV=production

# ファイルのオーナーを変更
# COPY --chown=node:node --from=build /app/dist /app/dist
# COPY --chown=node:node --from=node_modules /app/node_modules /app/node_modules
# USER node

COPY --from=build /app/dist /app/dist
COPY --from=node_modules /app/node_modules /app/node_modules

CMD ["dist/main"]
