#==================================================
# Build Layer
FROM node:16-slim as build

WORKDIR /app

RUN apt-get -qy update && apt-get -qy install openssl

COPY package.json yarn.lock ./

RUN yarn install --non-interactive --frozen-lockfile

COPY . .

RUN yarn build

RUN yarn prisma generate

RUN yarn lint
