# localもdockerなしでいいかもhttps://mizchi.hatenablog.com/entry/2019/04/07/074634
FROM node:16.14-slim
WORKDIR /app

RUN apt-get -qy update && apt-get -qy install openssl --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*
